//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoReservaTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int ReservaID { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public int EventoID { get; set; }
        public string NombreAepllido { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public int CantidadTicket { get; set; }
        public decimal TotalPagar { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
